# Site settings
title: Shaodong (Sheldon) Li
email: lispku@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Shaodong (Sheldon) Li's personal pages.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  lishaodong

# Build settings
markdown: kramdown
